In [1]:
import pandas as pd

In [4]:
bank_df = pd.read_csv("../archivos/BankChurners.csv")

In [5]:
bank_df.head(50)

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,...,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2
0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,...,12691.0,777,11914.0,1.335,1144,42,1.625,0.061,0.000093,0.999910
1,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,...,8256.0,864,7392.0,1.541,1291,33,3.714,0.105,0.000057,0.999940
2,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,...,3418.0,0,3418.0,2.594,1887,20,2.333,0.000,0.000021,0.999980
3,769911858,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,...,3313.0,2517,796.0,1.405,1171,20,2.333,0.760,0.000134,0.999870
4,709106358,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,...,4716.0,0,4716.0,2.175,816,28,2.500,0.000,0.000022,0.999980
5,713061558,Existing Customer,44,M,2,Graduate,Married,$40K - $60K,Blue,36,...,4010.0,1247,2763.0,1.376,1088,24,0.846,0.311,0.000055,0.999940
6,810347208,Existing Customer,51,M,4,Unknown,Married,$120K +,Gold,46,...,34516.0,2264,32252.0,1.975,1330,31,0.722,0.066,0.000123,0.999880
7,818906208,Existing Customer,32,M,0,High School,Unknown,$60K - $80K,Silver,27,...,29081.0,1396,27685.0,2.204,1538,36,0.714,0.048,0.000086,0.999910
8,710930508,Existing Customer,37,M,3,Uneducated,Single,$60K - $80K,Blue,36,...,22352.0,2517,19835.0,3.355,1350,24,1.182,0.113,0.000045,0.999960
9,719661558,Existing Customer,48,M,2,Graduate,Single,$80K - $120K,Blue,36,...,11656.0,1677,9979.0,1.524,1441,32,0.882,0.144,0.000303,0.999700
10,708790833,Existing Customer,42,M,5,Uneducated,Unknown,$120K +,Blue,31,...,6748.0,1467,5281.0,0.831,1201,42,0.680,0.217,0.000191,0.999810
11,710821833,Existing Customer,65,M,1,Unknown,Married,$40K - $60K,Blue,54,...,9095.0,1587,7508.0,1.433,1314,26,1.364,0.174,0.000198,0.999800
12,710599683,Existing Customer,56,M,1,College,Single,$80K - $120K,Blue,36,...,11751.0,0,11751.0,3.397,1539,17,3.250,0.000,0.000048,0.999950
13,816082233,Existing Customer,35,M,3,Graduate,Unknown,$60K - $80K,Blue,30,...,8547.0,1666,6881.0,1.163,1311,33,2.000,0.195,0.000096,0.999900
14,712396908,Existing Customer,57,F,2,Graduate,Married,Less than $40K,Blue,48,...,2436.0,680,1756.0,1.190,1570,29,0.611,0.279,0.000114,0.999890
15,714885258,Existing Customer,44,M,4,Unknown,Unknown,$80K - $120K,Blue,37,...,4234.0,972,3262.0,1.707,1348,27,1.700,0.230,0.000063,0.999940
16,709967358,Existing Customer,48,M,4,Post-Graduate,Single,$80K - $120K,Blue,36,...,30367.0,2362,28005.0,1.708,1671,27,0.929,0.078,0.000236,0.999760
17,753327333,Existing Customer,41,M,3,Unknown,Married,$80K - $120K,Blue,34,...,13535.0,1291,12244.0,0.653,1028,21,1.625,0.095,0.000150,0.999850
18,806160108,Existing Customer,61,M,1,High School,Married,$40K - $60K,Blue,56,...,3193.0,2517,676.0,1.831,1336,30,1.143,0.788,0.000175,0.999830
19,709327383,Existing Customer,45,F,2,Graduate,Married,Unknown,Blue,37,...,14470.0,1157,13313.0,0.966,1207,21,0.909,0.080,0.000055,0.999940
20,806165208,Existing Customer,47,M,1,Doctorate,Divorced,$60K - $80K,Blue,42,...,20979.0,1800,19179.0,0.906,1178,27,0.929,0.086,0.000057,0.999940
21,708508758,Attrited Customer,62,F,0,Graduate,Married,Less than $40K,Blue,49,...,1438.3,0,1438.3,1.047,692,16,0.600,0.000,0.996160,0.003836
22,784725333,Existing Customer,41,M,3,High School,Married,$40K - $60K,Blue,33,...,4470.0,680,3790.0,1.608,931,18,1.571,0.152,0.000069,0.999930
23,811604133,Existing Customer,47,F,4,Unknown,Single,Less than $40K,Blue,36,...,2492.0,1560,932.0,0.573,1126,23,0.353,0.626,0.000207,0.999790
24,789124683,Existing Customer,54,M,2,Unknown,Married,$80K - $120K,Blue,42,...,12217.0,0,12217.0,1.075,1110,21,0.750,0.000,0.000210,0.999790
25,771071958,Existing Customer,41,F,3,Graduate,Single,Less than $40K,Blue,28,...,7768.0,1669,6099.0,0.797,1051,22,0.833,0.215,0.000057,0.999940
26,720466383,Existing Customer,59,M,1,High School,Unknown,$40K - $60K,Blue,46,...,14784.0,1374,13410.0,0.921,1197,23,1.300,0.093,0.000050,0.999950
27,804424383,Existing Customer,63,M,1,Unknown,Married,$60K - $80K,Blue,56,...,10215.0,1010,9205.0,0.843,1904,40,1.000,0.099,0.000186,0.999810
28,718813833,Existing Customer,44,F,3,Uneducated,Single,Unknown,Blue,34,...,10100.0,0,10100.0,0.525,1052,18,1.571,0.000,0.000121,0.999880
29,806624208,Existing Customer,47,M,4,High School,Married,$40K - $60K,Blue,42,...,4785.0,1362,3423.0,0.739,1045,38,0.900,0.285,0.000008,0.999990
30,778348233,Existing Customer,53,M,3,Unknown,Married,$80K - $120K,Blue,33,...,2753.0,1811,942.0,0.977,1038,25,2.571,0.658,0.000218,0.999780
31,712991808,Existing Customer,53,M,2,Uneducated,Married,$60K - $80K,Blue,48,...,2451.0,1690,761.0,1.323,1596,26,1.600,0.690,0.000125,0.999880
32,709029408,Existing Customer,41,M,4,Graduate,Married,$60K - $80K,Blue,36,...,8923.0,2517,6406.0,1.726,1589,24,1.667,0.282,0.000058,0.999940
33,788658483,Existing Customer,53,F,2,College,Married,Less than $40K,Blue,38,...,2650.0,1490,1160.0,1.750,1411,28,1.000,0.562,0.000186,0.999810
34,787937058,Existing Customer,58,M,0,Graduate,Married,$80K - $120K,Blue,49,...,12555.0,1696,10859.0,0.519,1291,24,0.714,0.135,0.000098,0.999900
35,715318008,Existing Customer,55,F,1,College,Single,Less than $40K,Blue,36,...,3520.0,1914,1606.0,0.510,1407,43,0.483,0.544,0.000063,0.999940
36,713962233,Existing Customer,55,F,3,Graduate,Married,Less than $40K,Blue,36,...,3035.0,2298,737.0,1.724,1877,37,1.176,0.757,0.000199,0.999800
37,785432733,Existing Customer,42,F,4,High School,Married,Less than $40K,Gold,36,...,15433.0,0,15433.0,0.865,966,22,1.200,0.000,0.000355,0.999640
38,715190283,Existing Customer,57,F,1,Graduate,Unknown,$40K - $60K,Blue,49,...,3672.0,886,2786.0,1.320,1464,28,0.556,0.241,0.000169,0.999830
39,708300483,Attrited Customer,66,F,0,Doctorate,Married,Unknown,Blue,56,...,7882.0,605,7277.0,1.052,704,16,0.143,0.077,0.997800,0.002197
40,827111283,Existing Customer,45,M,3,Graduate,Single,$80K - $120K,Blue,41,...,32426.0,578,31848.0,1.042,1109,28,0.474,0.018,0.000118,0.999880
41,758551608,Existing Customer,51,M,2,Unknown,Married,$40K - $60K,Blue,44,...,6205.0,2204,4001.0,0.803,1347,28,0.556,0.355,0.000022,0.999980
42,773146383,Existing Customer,50,F,1,College,Single,$40K - $60K,Silver,43,...,17304.0,2517,14787.0,1.449,1756,33,1.200,0.145,0.000158,0.999840
43,778493808,Existing Customer,49,M,3,High School,Married,$60K - $80K,Blue,37,...,3906.0,0,3906.0,1.214,1756,32,1.000,0.000,0.000069,0.999930
44,720572508,Existing Customer,38,F,4,Graduate,Single,Unknown,Blue,28,...,9830.0,2055,7775.0,0.977,1042,23,0.917,0.209,0.000317,0.999680
45,712661433,Existing Customer,49,M,4,Uneducated,Single,$80K - $120K,Blue,30,...,34516.0,0,34516.0,1.621,1444,28,1.333,0.000,0.000206,0.999790
46,789172683,Existing Customer,56,M,2,Doctorate,Married,$60K - $80K,Blue,45,...,2283.0,1430,853.0,2.316,1741,27,0.588,0.626,0.000061,0.999940
47,738406533,Existing Customer,59,M,1,Doctorate,Married,$40K - $60K,Blue,52,...,2548.0,2020,528.0,2.357,1719,27,1.700,0.793,0.000155,0.999850
48,799723908,Existing Customer,46,M,3,High School,Married,$80K - $120K,Blue,40,...,19458.0,1435,18023.0,0.787,1217,27,0.800,0.074,0.000305,0.999690
49,771490833,Existing Customer,52,M,1,College,Single,$80K - $120K,Blue,40,...,4745.0,1227,3518.0,0.624,1140,40,0.600,0.259,0.000030,0.999970

In [9]:
num_filas = bank_df.shape[0]
num_columnas = bank_df.shape[1]

print(f"El archivo tiene {num_filas} filas y {num_columnas} columnas.")

El archivo tiene 10127 filas y 23 columnas.